services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 54329:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

volumes:
  postgres-db-volume: